/**************************************************************
 * 文件名称:  gtfCommon.h
 * 作           者:  keith.gong
 * 日           期:  2015.12.16
 * 文件描述:  
 * 版           本:  V1.00
 * 修改历史:  
 *     <修改者>   <时间>    <版本 >   <描述>
**************************************************************/


#ifndef __GCOMMON_H__
#define __GCOMMON_H__

#include "sys_debug.h"

typedef enum
{
    ONUCFG_RESULT_INIT,
    ONUCFG_RESULT_SUCCESS,
    ONUCFG_RESULT_FAILED,
    ONUCFG_RESULT_CONFIGING,
}ONUCFG_RESULT_DTE;


typedef enum
{
    GRTN_OK,
    GRTN_ERROR,

    /* 通用错误*/
    GRTN_ERROR_MALLOC,              /* 内存不足*/
    GRTN_ERROR_INVALID_PARAM,       /* 参数错误*/
    GRTN_ERROR_NOT_SUPPORT,
    GRTN_ERROR_TIMEOUT,
    GRTN_CONFIG_REPEAT,
    GRTN_CONFIG_CONFLICT,
    GRTN_CONFIG_SYNC_CONFLICT,
    GRTN_ERROR_OMCI_PROCESS_FAILED,
    
    /* 模板存在性错误*/
    GRTN_DBA_PROFILE_EXIST,             /* 模板已存在*/
    GRTN_DBA_PROFILE_NOT_EXIST,         /* 模板不存在 10*/
    GRTN_DBA_PROFILE_BOUND,
    GRTN_DBA_PROFILE_TABLE_FULL,        /* 模板数量达到上限*/
    
    GRTN_SRV_PROFILE_EXIST,             /* 模板已存在*/
    GRTN_SRV_PROFILE_NOT_EXIST,         /* 模板不存在*/
    GRTN_SRV_PROFILE_BOUND,
    GRTN_SRV_PROFILE_TABLE_FULL,        /* 模板数量达到上限*/
    GRTN_SRV_PROFILE_USED_AUTOAUTH,
    
    GRTN_LINE_PROFILE_EXIST,             /* 模板已存在*/
    GRTN_LINE_PROFILE_NOT_EXIST,         /* 模板不存在*/
    GRTN_LINE_PROFILE_BOUND,             //20
    GRTN_LINE_PROFILE_TABLE_FULL,        /* 模板数量达到上限*/
    GRTN_LINE_PROFILE_USED_AUTOAUTH,

    GRTN_SLA_PROFILE_EXIST,             /* 模板已存在*/
    GRTN_SLA_PROFILE_NOT_EXIST,         /* 模板不存在*/
    GRTN_SLA_PROFILE_BOUND,
    GRTN_SLA_PROFILE_NOT_BOUND,
    GRTN_SLA_PROFILE_TABLE_FULL,        /* 模板数量达到上限*/

    GRTN_ALARM_PROFILE_EXIST,             /* 模板已存在*/
    GRTN_ALARM_PROFILE_NOT_EXIST,         /* 模板不存在*/
    GRTN_ALARM_PROFILE_BOUND,             //30
    GRTN_ALARM_PROFILE_NOT_BOUND,
    GRTN_ALARM_PROFILE_TABLE_FULL,        /* 模板数量达到上限*/    

    GRTN_OPTICAL_ALARM_PROFILE_EXIST,             /* 模板已存在*/
    GRTN_OPTICAL_ALARM_PROFILE_NOT_EXIST,         /* 模板不存在*/
    GRTN_OPTICAL_ALARM_PROFILE_BOUND,
    GRTN_OPTICAL_ALARM_PROFILE_NOT_BOUND,
    GRTN_OPTICAL_ALARM_PROFILE_TABLE_FULL,        /* 模板数量达到上限*/  

    GRTN_CLASSIFICATION_PROFILE_EXIST,             /* 模板已存在*/
    GRTN_CLASSIFICATION_PROFILE_NOT_EXIST,         /* 模板不存在*/
    GRTN_CLASSIFICATION_PROFILE_BOUND,             //40
    GRTN_CLASSIFICATION_PROFILE_NOT_BOUND,
    GRTN_CLASSIFICATION_PROFILE_TABLE_FULL,        /* 模板数量达到上限*/

    GRTN_SIPAGENT_PROFILE_EXIST,             /* 模板已存在*/
    GRTN_SIPAGENT_PROFILE_NOT_EXIST,         /* 模板不存在*/
    GRTN_SIPAGENT_PROFILE_BOUND,
    GRTN_SIPAGENT_PROFILE_TABLE_FULL,        /* 模板数量达到上限*/

    GRTN_POTS_PROFILE_EXIST,             /* 模板已存在*/
    GRTN_POTS_PROFILE_NOT_EXIST,         /* 模板不存在*/
    GRTN_POTS_PROFILE_BOUND,
    GRTN_POTS_PROFILE_TABLE_FULL,        /* 模板数量达到上限 50*/

    GRTN_DIGITMAP_PROFILE_EXIST,             /* 模板已存在*/
    GRTN_DIGITMAP_PROFILE_NOT_EXIST,         /* 模板不存在*/
    GRTN_DIGITMAP_PROFILE_BOUND,
    GRTN_DIGITMAP_PROFILE_TABLE_FULL,        /* 模板数量达到上限*/

    GRTN_SIPRIGHT_PROFILE_EXIST,             /* 模板已存在*/
    GRTN_SIPRIGHT_PROFILE_NOT_EXIST,         /* 模板不存在*/
    GRTN_SIPRIGHT_PROFILE_BOUND,
    GRTN_SIPRIGHT_PROFILE_TABLE_FULL,        /* 模板数量达到上限*/

    GRTN_TRAFFIC_PROFILE_EXIST,             /* 模板已存在*/
    GRTN_TRAFFIC_PROFILE_NOT_EXIST,         /* 模板不存在 60*/
    GRTN_TRAFFIC_PROFILE_BOUND,
    GRTN_TRAFFIC_PROFILE_NOT_BOUND,
    GRTN_TRAFFIC_PROFILE_TABLE_FULL,        /* 模板数量达到上限*/

    /* 模板绑定错误*/
    GRTN_ERROR_ONU_BOUND,
    GRTN_ERROR_ONU_NOT_BOUND,

    /* ONU 状态*/
    GRTN_ONU_NOT_EXIST,//66
    GRTN_ONU_NOT_ONLINE,
    GRTN_ONU_IDLE,
    GRTN_ONU_BUSY,
    GRTN_ONU_MIB_SYNCED,//70
    GRTN_ONU_MIB_NOT_SYNCED,

    /* 授权状态错误*/
    GRTN_ERROR_ONURA_ONU_HAS_NOT_REGED,
    GRTN_ERROR_ONURA_ONU_ALREADY_AUTHED,
    GRTN_ERROR_ONURA_AUTH_LIST_TABLE_FULL,
    GRTN_ERROR_ONURA_AUTH_ENTRY_NOT_EXIST,
    GRTN_ERROR_ONURA_AUTH_ENTRY_EXIST,
    GRTN_ERROR_ONURA_AUTH_ENTRY_CONFLLIC,
    GRTN_ERROR_ONURA_AUTH_NO_UNUSED_AUTHID,
    
    /*注册状态错误*/
    GRTN_ONURA_ERROR_REG_LIST_TABLE_FULL,
    GRTN_ONURA_ERROR_REG_ENTRY_NOT_EXIST,//80
    GRTN_ONURA_ERROR_REG_ENTRY_EXIST, 
    GRTN_ONURA_ERROR_REG_ENTRY_CONFLLIC,
    GRTN_ONURA_ERROR_REG_ENTRY_ID_USED,
    GRTN_ONURA_ERROR_REG_ENTRY_SN_REGED,

    /*注册状态错误*/
    GRTN_ONURA_ERROR_BLACKLIST_TABLE_FULL,
    GRTN_ONURA_ERROR_BLACKLIST_ENTRY_NOT_EXIST,
    GRTN_ONURA_ERROR_BLACKLIST_ENTRY_CONFLLIC,
    
    /* 物理状态配置错误*/
    GRTN_ONURA_ERROR_SILENCE_FAILED,
    GRTN_ONURA_ERROR_DESILENCE_FAILED,
    GRTN_ONURA_ERROR_OFFLINE_FAILED,//90

    GRTN_NO_ENOUGHT_BW,             /* 带宽溢出*/

    GRTN_ERROR_ETH_PORT_NOT_EXIST,
    GRTN_ERROR_ETH_PORT_NOT_ADD_TO_THE_VLAN,

	GRTN_ERROR_POTS_PORT_NOT_EXIST,
    GRTN_ERROR_POTS_PORT_USER_EXIST,
    GRTN_ERROR_POTS_PORT_USER_NOT_EXIST,

    GRTN_ONU_IPCONFIG_NOT_CONFIGURED,

    GRTN_ONU_UPGRADE_LOAD_START,
    GRTN_ONU_UPGRADE_LOAD_STOP,
    GRTN_ONU_UPGRADE_LOADING,//100
    GRTN_ONU_UPGRADE_NOT_SELECT,
    GRTN_ONU_UPGRADE_SELECT,
    GRTN_ONU_UPGRADE_DOWNLOAD_FAILED,
    GRTN_ONU_UPGRADE_IMAGE_DOWNLOADING,    
    GRTN_ONU_UPGRADE_OPEN_FAILED,
    GRTN_ONU_UPGRADE_IMAGE_SIZE_ERROR,
    GRTN_ONU_UPGRADE_IMAGE_READED,

    GRTN_ONU_AUTOAUTH_MODE_CONFLICT,
    GRTN_ONU_AUTOAUTH_RULE_ENTRY_EXIST,
    GRTN_ONU_AUTOAUTH_RULE_CONFLICT,//110
    GRTN_ONU_AUTOAUTH_RULE_FULL,
    
    ERTN_ACL_PROFILE_ID_INVALID,
    ERTN_ACL_PROFILE_IN_USE,
    ERTN_ACL_INVALID,
    ERTN_ACL_BIND_FULL,
    ERTN_ACL_BIND_AGAIN,
    ERTN_ACL_BIND_NOT_EXIST,
    ERTN_ACL_BIND_FAILED,

    GRTN_LINE_PROFILE_BOUND_BY_AUTOAUTH,
    GRTN_SRV_PROFILE_BOUND_BY_AUTOAUTH,//120

    PROFILE_RTN_MAX,
}GRTN_CODE;


typedef struct 
{
    const char          *pMsg;
    const char          *pFormat;
}
GERROR_MSG;

typedef struct 
{
    const char          *pMsg;
    const char          *pFormat;
}
GALARM_MSG;

const char *
gerrorcode_print(
                GRTN_CODE ret);

const char *
rc_simple_print(
                unsigned int ret);             

#endif /* __GCOMMON_H__ */


